proyecto:
	pdflatex proyecto.tex
	pdflatex proyecto.tex

clean:	
	rm *.log *.toc *.aux *.out

tlmgr:
	tlmgr init-usertree
	tlmgr install babel-spaninsh
	tlmgr install geometry
	tlmgr install fancyhdr
	tlmgr install multirow
	tlmgr install hyperref

